name: Step 6, Trigger Your Action

# This step listens for the learner applying a label to an issue.
# This workflow updates from step 6 to step X.

on:
  workflow_dispatch:
  issues:
    types: [labeled]

permissions:
  # Need `contents: read` to checkout the repository.
  # Need `contents: write` to update the step metadata.
  contents: write

env:
  EXPECTED_METADATA: "second joke"

jobs:
  # Get the current step to only run the main job when the learner is on the same step.
  get_current_step:
    name: Check current step number
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: get_step
        run: |
          echo "current_step=$(cat ./.github/steps/-step.txt)" >> $GITHUB_OUTPUT
    outputs:
      current_step: ${{ steps.get_step.outputs.current_step }}

  on_my_workflow_run:
    name: Check if my_workflow has run
    needs: get_current_step

    # We will only run this action when:
    # 1. This repository isn't the template repository.
    # 2. The step is currently 6.
    if: >-
      ${{ !github.event.repository.is_template
          && needs.get_current_step.outputs.current_step == '6' }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Let's get all the branches.

      - name: Dump GitHub comment context
        id: github_comment_step
        run: echo '${{ toJSON(github.event) }}'

      # Update README from step 6 to step X.
      - name: Update to step X
        if: contains(github.event.label.name, env.EXPECTED_METADATA)
        uses: skills/action-update-step@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          from_step: 6
          to_step: X
